/**
 * NecroNet - on_ui_generate Hook
 * 
 * Triggered when a UI component generation is requested.
 * Automatically generates React components with necro-gothic theme,
 * Tailwind CSS styling, and Framer Motion animations.
 * 
 * Requirements: 4.1, 4.2, 4.3, 4.4, 4.5, 9.2, 9.4
 */

/**
 * Necro-gothic theme colors
 */
const NECRO_THEME = {
  colors: {
    void: '#0f0a1f',      // Deep background
    arcane: '#a800ff',    // Primary accent (purple)
    blood: '#ff0055',     // Secondary accent (red)
    ghost: '#19ff90',     // Success/active (green)
  },
  fonts: {
    mono: '"Fira Code", "Courier New", monospace',
    display: '"Orbitron", sans-serif',
  },
};

/**
 * Generate a React component with necro-gothic styling
 * 
 * @param {Object} options - Component generation options
 * @returns {string} Generated component code
 */
function generateComponent(options) {
  const {
    name = 'NecroComponent',
    props = [],
    type = 'functional',
    includeAnimation = true,
    includeStyles = true,
  } = options;
  
  // Determine component type
  const componentTypes = {
    button: generateButton,
    card: generateCard,
    header: generateHeader,
    modal: generateModal,
    form: generateForm,
    list: generateList,
    functional: generateFunctionalComponent,
  };
  
  const generator = componentTypes[type] || componentTypes.functional;
  
  return generator(name, props, includeAnimation, includeStyles);
}

/**
 * Generate a functional component template
 */
function generateFunctionalComponent(name, props, includeAnimation, includeStyles) {
  const propsInterface = generatePropsInterface(name, props);
  const propsDestructure = props.length > 0 ? `{ ${props.map(p => p.name).join(', ')} }` : '';
  const propsType = props.length > 0 ? `: ${name}Props` : '';
  
  const imports = [
    "import React from 'react';",
  ];
  
  if (includeAnimation) {
    imports.push("import { motion } from 'framer-motion';");
  }
  
  const animationProps = includeAnimation ? `
  initial={{ opacity: 0, y: 20 }}
  animate={{ opacity: 1, y: 0 }}
  transition={{ duration: 0.5 }}` : '';
  
  const componentTag = includeAnimation ? 'motion.div' : 'div';
  
  return `${imports.join('\n')}

${propsInterface}

/**
 * ${name} - A necro-gothic component
 * Generated by NecroNet UI Generator
 */
export default function ${name}(${propsDestructure}${propsType}) {
  return (
    <${componentTag}
      className="necro-${name.toLowerCase()}"${animationProps}
    >
      <div className="necro-content">
        <h2 className="necro-title">☠️ ${name} ☠️</h2>
        ${props.length > 0 ? generatePropsDisplay(props) : '<p className="necro-text">Component content goes here</p>'}
      </div>
    </${componentTag}>
  );
}

${includeStyles ? generateComponentStyles(name) : ''}
`;
}

/**
 * Generate a button component
 */
function generateButton(name, props, includeAnimation) {
  return `import React from 'react';
import { motion } from 'framer-motion';

interface ${name}Props {
  onClick?: () => void;
  children: React.ReactNode;
  variant?: 'primary' | 'secondary' | 'danger';
  disabled?: boolean;
}

/**
 * ${name} - A necro-gothic button with glowing effects
 */
export default function ${name}({
  onClick,
  children,
  variant = 'primary',
  disabled = false,
}: ${name}Props) {
  const variantClasses = {
    primary: 'bg-arcane hover:bg-arcane/80 text-void',
    secondary: 'bg-ghost hover:bg-ghost/80 text-void',
    danger: 'bg-blood hover:bg-blood/80 text-void',
  };
  
  return (
    <motion.button
      onClick={onClick}
      disabled={disabled}
      className={\`necro-button \${variantClasses[variant]} \${disabled ? 'opacity-50 cursor-not-allowed' : ''}\`}
      whileHover={{ scale: disabled ? 1 : 1.05 }}
      whileTap={{ scale: disabled ? 1 : 0.95 }}
      transition={{ duration: 0.2 }}
    >
      {children}
    </motion.button>
  );
}

/* Styles */
const styles = \`
.necro-button {
  padding: 0.75rem 1.5rem;
  border: none;
  border-radius: 0.5rem;
  font-family: ${NECRO_THEME.fonts.mono};
  font-weight: bold;
  font-size: 1rem;
  cursor: pointer;
  box-shadow: 0 0 20px currentColor;
  transition: all 0.3s ease;
}

.necro-button:hover:not(:disabled) {
  box-shadow: 0 0 30px currentColor;
}
\`;
`;
}

/**
 * Generate a card component
 */
function generateCard(name, props, includeAnimation) {
  return `import React from 'react';
import { motion } from 'framer-motion';

interface ${name}Props {
  title: string;
  children: React.ReactNode;
  glowColor?: 'arcane' | 'blood' | 'ghost';
}

/**
 * ${name} - A necro-gothic card with hover effects
 */
export default function ${name}({
  title,
  children,
  glowColor = 'arcane',
}: ${name}Props) {
  const glowColors = {
    arcane: '#a800ff',
    blood: '#ff0055',
    ghost: '#19ff90',
  };
  
  return (
    <motion.div
      className="necro-card"
      style={{ '--glow-color': glowColors[glowColor] } as React.CSSProperties}
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      whileHover={{ y: -5 }}
      transition={{ duration: 0.3 }}
    >
      <h3 className="necro-card-title">{title}</h3>
      <div className="necro-card-content">
        {children}
      </div>
    </motion.div>
  );
}

/* Styles */
const styles = \`
.necro-card {
  background: rgba(168, 0, 255, 0.1);
  border: 2px solid var(--glow-color, #a800ff);
  border-radius: 0.5rem;
  padding: 1.5rem;
  box-shadow: 0 0 20px var(--glow-color, #a800ff);
  transition: all 0.3s ease;
}

.necro-card:hover {
  box-shadow: 0 0 30px var(--glow-color, #a800ff);
}

.necro-card-title {
  color: var(--glow-color, #a800ff);
  font-size: 1.5rem;
  margin: 0 0 1rem 0;
  font-family: ${NECRO_THEME.fonts.display};
}

.necro-card-content {
  color: ${NECRO_THEME.colors.ghost};
  font-family: ${NECRO_THEME.fonts.mono};
}
\`;
`;
}

/**
 * Generate a header component
 */
function generateHeader(name, props, includeAnimation) {
  return `import React from 'react';
import { motion } from 'framer-motion';

interface ${name}Props {
  title: string;
  subtitle?: string;
  soulCount?: number;
}

/**
 * ${name} - A necro-gothic header with soul counter
 */
export default function ${name}({
  title,
  subtitle,
  soulCount = 0,
}: ${name}Props) {
  return (
    <motion.header
      className="necro-header"
      initial={{ opacity: 0, y: -50 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6 }}
    >
      <div className="necro-header-content">
        <motion.h1
          className="necro-header-title"
          animate={{ opacity: [1, 0.7, 1] }}
          transition={{ duration: 2, repeat: Infinity }}
        >
          ☠️ {title} ☠️
        </motion.h1>
        {subtitle && (
          <p className="necro-header-subtitle">{subtitle}</p>
        )}
      </div>
      
      {soulCount > 0 && (
        <motion.div
          className="necro-soul-counter"
          animate={{ scale: [1, 1.1, 1] }}
          transition={{ duration: 1.5, repeat: Infinity }}
        >
          <span className="soul-count">{soulCount}</span>
          <span className="soul-label">Souls Resurrected</span>
        </motion.div>
      )}
    </motion.header>
  );
}

/* Styles */
const styles = \`
.necro-header {
  background: linear-gradient(180deg, ${NECRO_THEME.colors.void} 0%, transparent 100%);
  padding: 2rem;
  text-align: center;
  border-bottom: 2px solid ${NECRO_THEME.colors.arcane};
}

.necro-header-title {
  font-size: 3rem;
  color: ${NECRO_THEME.colors.arcane};
  text-shadow: 0 0 20px ${NECRO_THEME.colors.arcane};
  font-family: ${NECRO_THEME.fonts.display};
  margin: 0;
}

.necro-header-subtitle {
  font-size: 1.2rem;
  color: ${NECRO_THEME.colors.ghost};
  opacity: 0.8;
  font-family: ${NECRO_THEME.fonts.mono};
  margin: 0.5rem 0 0 0;
}

.necro-soul-counter {
  display: inline-flex;
  flex-direction: column;
  align-items: center;
  margin-top: 1rem;
  padding: 1rem 2rem;
  background: rgba(168, 0, 255, 0.2);
  border: 2px solid ${NECRO_THEME.colors.arcane};
  border-radius: 0.5rem;
  box-shadow: 0 0 20px ${NECRO_THEME.colors.arcane};
}

.soul-count {
  font-size: 2rem;
  font-weight: bold;
  color: ${NECRO_THEME.colors.ghost};
  font-family: ${NECRO_THEME.fonts.display};
}

.soul-label {
  font-size: 0.875rem;
  color: ${NECRO_THEME.colors.arcane};
  font-family: ${NECRO_THEME.fonts.mono};
  text-transform: uppercase;
}
\`;
`;
}

/**
 * Generate a modal component
 */
function generateModal(name, props, includeAnimation) {
  return `import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';

interface ${name}Props {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  children: React.ReactNode;
}

/**
 * ${name} - A necro-gothic modal with backdrop
 */
export default function ${name}({
  isOpen,
  onClose,
  title,
  children,
}: ${name}Props) {
  return (
    <AnimatePresence>
      {isOpen && (
        <>
          <motion.div
            className="necro-modal-backdrop"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
          />
          <motion.div
            className="necro-modal"
            initial={{ opacity: 0, scale: 0.8, y: 50 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.8, y: 50 }}
            transition={{ duration: 0.3 }}
          >
            <div className="necro-modal-header">
              <h2 className="necro-modal-title">☠️ {title} ☠️</h2>
              <button
                className="necro-modal-close"
                onClick={onClose}
                aria-label="Close"
              >
                ✕
              </button>
            </div>
            <div className="necro-modal-content">
              {children}
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}

/* Styles */
const styles = \`
.necro-modal-backdrop {
  position: fixed;
  inset: 0;
  background: rgba(15, 10, 31, 0.9);
  z-index: 1000;
}

.necro-modal {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background: ${NECRO_THEME.colors.void};
  border: 2px solid ${NECRO_THEME.colors.arcane};
  border-radius: 0.5rem;
  box-shadow: 0 0 40px ${NECRO_THEME.colors.arcane};
  max-width: 90%;
  max-height: 90%;
  overflow: auto;
  z-index: 1001;
}

.necro-modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1.5rem;
  border-bottom: 1px solid ${NECRO_THEME.colors.arcane};
}

.necro-modal-title {
  color: ${NECRO_THEME.colors.arcane};
  font-family: ${NECRO_THEME.fonts.display};
  margin: 0;
}

.necro-modal-close {
  background: none;
  border: none;
  color: ${NECRO_THEME.colors.blood};
  font-size: 1.5rem;
  cursor: pointer;
  padding: 0.5rem;
  transition: transform 0.2s;
}

.necro-modal-close:hover {
  transform: scale(1.2);
}

.necro-modal-content {
  padding: 1.5rem;
  color: ${NECRO_THEME.colors.ghost};
  font-family: ${NECRO_THEME.fonts.mono};
}
\`;
`;
}

/**
 * Generate a form component
 */
function generateForm(name, props, includeAnimation) {
  return `import React, { useState } from 'react';
import { motion } from 'framer-motion';

interface ${name}Props {
  onSubmit: (data: Record<string, any>) => void;
  fields: Array<{ name: string; label: string; type: string }>;
}

/**
 * ${name} - A necro-gothic form with validation
 */
export default function ${name}({ onSubmit, fields }: ${name}Props) {
  const [formData, setFormData] = useState<Record<string, any>>({});
  
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit(formData);
  };
  
  const handleChange = (name: string, value: any) => {
    setFormData(prev => ({ ...prev, [name]: value }));
  };
  
  return (
    <motion.form
      className="necro-form"
      onSubmit={handleSubmit}
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5 }}
    >
      {fields.map((field, index) => (
        <motion.div
          key={field.name}
          className="necro-form-field"
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: index * 0.1 }}
        >
          <label className="necro-label" htmlFor={field.name}>
            {field.label}
          </label>
          <input
            id={field.name}
            type={field.type}
            className="necro-input"
            value={formData[field.name] || ''}
            onChange={(e) => handleChange(field.name, e.target.value)}
          />
        </motion.div>
      ))}
      
      <motion.button
        type="submit"
        className="necro-submit"
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
      >
        ⚡ Submit Ritual ⚡
      </motion.button>
    </motion.form>
  );
}

/* Styles */
const styles = \`
.necro-form {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.necro-form-field {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.necro-label {
  color: ${NECRO_THEME.colors.arcane};
  font-family: ${NECRO_THEME.fonts.mono};
  font-weight: bold;
}

.necro-input {
  background: rgba(168, 0, 255, 0.1);
  border: 2px solid ${NECRO_THEME.colors.arcane};
  border-radius: 0.25rem;
  padding: 0.75rem;
  color: ${NECRO_THEME.colors.ghost};
  font-family: ${NECRO_THEME.fonts.mono};
  transition: all 0.3s ease;
}

.necro-input:focus {
  outline: none;
  border-color: ${NECRO_THEME.colors.ghost};
  box-shadow: 0 0 10px ${NECRO_THEME.colors.ghost};
}

.necro-submit {
  background: ${NECRO_THEME.colors.arcane};
  color: ${NECRO_THEME.colors.void};
  border: none;
  border-radius: 0.5rem;
  padding: 1rem;
  font-family: ${NECRO_THEME.fonts.mono};
  font-weight: bold;
  font-size: 1rem;
  cursor: pointer;
  box-shadow: 0 0 20px ${NECRO_THEME.colors.arcane};
  transition: all 0.3s ease;
}

.necro-submit:hover {
  box-shadow: 0 0 30px ${NECRO_THEME.colors.arcane};
}
\`;
`;
}

/**
 * Generate a list component
 */
function generateList(name, props, includeAnimation) {
  return `import React from 'react';
import { motion } from 'framer-motion';

interface ${name}Props {
  items: Array<{ id: string; content: React.ReactNode }>;
  onItemClick?: (id: string) => void;
}

/**
 * ${name} - A necro-gothic list with staggered animations
 */
export default function ${name}({ items, onItemClick }: ${name}Props) {
  return (
    <motion.ul
      className="necro-list"
      initial="hidden"
      animate="visible"
      variants={{
        visible: {
          transition: {
            staggerChildren: 0.1,
          },
        },
      }}
    >
      {items.map((item) => (
        <motion.li
          key={item.id}
          className="necro-list-item"
          variants={{
            hidden: { opacity: 0, x: -20 },
            visible: { opacity: 1, x: 0 },
          }}
          whileHover={{ x: 10, scale: 1.02 }}
          onClick={() => onItemClick?.(item.id)}
        >
          <span className="necro-list-bullet">☠️</span>
          <span className="necro-list-content">{item.content}</span>
        </motion.li>
      ))}
    </motion.ul>
  );
}

/* Styles */
const styles = \`
.necro-list {
  list-style: none;
  padding: 0;
  margin: 0;
}

.necro-list-item {
  display: flex;
  align-items: center;
  gap: 1rem;
  padding: 1rem;
  margin-bottom: 0.5rem;
  background: rgba(168, 0, 255, 0.1);
  border: 1px solid ${NECRO_THEME.colors.arcane};
  border-radius: 0.25rem;
  cursor: pointer;
  transition: all 0.3s ease;
}

.necro-list-item:hover {
  background: rgba(168, 0, 255, 0.2);
  box-shadow: 0 0 15px ${NECRO_THEME.colors.arcane};
}

.necro-list-bullet {
  color: ${NECRO_THEME.colors.blood};
  font-size: 1.2rem;
}

.necro-list-content {
  color: ${NECRO_THEME.colors.ghost};
  font-family: ${NECRO_THEME.fonts.mono};
  flex: 1;
}
\`;
`;
}

/**
 * Generate TypeScript props interface
 */
function generatePropsInterface(name, props) {
  if (props.length === 0) return '';
  
  const propsLines = props.map(prop => {
    const optional = prop.required === false ? '?' : '';
    return `  ${prop.name}${optional}: ${prop.type};`;
  });
  
  return `interface ${name}Props {
${propsLines.join('\n')}
}
`;
}

/**
 * Generate props display in component
 */
function generatePropsDisplay(props) {
  return props.map(prop => 
    `        <p className="necro-prop">
          <span className="prop-name">{${prop.name}}</span>
        </p>`
  ).join('\n');
}

/**
 * Generate component-specific styles
 */
function generateComponentStyles(name) {
  return `
/* Styles for ${name} */
const styles = \`
.necro-${name.toLowerCase()} {
  background: rgba(168, 0, 255, 0.1);
  border: 2px solid ${NECRO_THEME.colors.arcane};
  border-radius: 0.5rem;
  padding: 2rem;
  box-shadow: 0 0 20px ${NECRO_THEME.colors.arcane};
}

.necro-content {
  color: ${NECRO_THEME.colors.ghost};
  font-family: ${NECRO_THEME.fonts.mono};
}

.necro-title {
  color: ${NECRO_THEME.colors.arcane};
  font-family: ${NECRO_THEME.fonts.display};
  font-size: 2rem;
  margin: 0 0 1rem 0;
  text-shadow: 0 0 10px ${NECRO_THEME.colors.arcane};
}

.necro-text {
  color: ${NECRO_THEME.colors.ghost};
  line-height: 1.6;
}

.necro-prop {
  margin: 0.5rem 0;
}

.prop-name {
  color: ${NECRO_THEME.colors.ghost};
  font-weight: bold;
}
\`;
`;
}

/**
 * Main hook handler
 * 
 * @param {Object} context - Hook context with component information
 * @returns {Promise<Object>} Result with generated component code
 */
module.exports = async function onUiGenerate(context) {
  try {
    console.log('\n☠️ === UI GENERATION RITUAL === ☠️\n');
    
    const {
      componentName = 'NecroComponent',
      componentType = 'functional',
      props = [],
      includeAnimation = true,
      includeStyles = true,
    } = context;
    
    console.log(`🔮 Conjuring ${componentType} component: ${componentName}`);
    console.log(`⚡ Theme: Necro-Gothic`);
    console.log(`✨ Animations: ${includeAnimation ? 'Enabled' : 'Disabled'}`);
    console.log(`🎨 Styles: ${includeStyles ? 'Included' : 'External'}`);
    
    // Generate the component
    const componentCode = generateComponent({
      name: componentName,
      props,
      type: componentType,
      includeAnimation,
      includeStyles,
    });
    
    console.log(`\n✅ Component generated successfully!`);
    console.log(`📝 Lines of code: ${componentCode.split('\n').length}`);
    console.log(`🎨 Theme colors applied: void, arcane, blood, ghost`);
    
    if (includeAnimation) {
      console.log(`💫 Framer Motion animations integrated`);
    }
    
    console.log('\n☠️ === MANIFESTATION COMPLETE === ☠️\n');
    
    return {
      success: true,
      code: componentCode,
      componentName,
      componentType,
      theme: NECRO_THEME,
      message: `✨ summon(): ${componentName} materialized from the void ✨`,
      occultMessage: '🌟 The component walks among the living code 🌟',
    };
    
  } catch (error) {
    console.error('💀 UI GENERATION FAILED:', error.message);
    
    return {
      success: false,
      error: error.message,
      message: '💀 The manifestation ritual has failed 💀',
      occultMessage: '🌑 The component refuses to take form 🌑',
    };
  }
};

// Export helper functions for testing
module.exports.generateComponent = generateComponent;
module.exports.NECRO_THEME = NECRO_THEME;
